In [2]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32)
print(repr(arr))


array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [3]:
arr = np.array([0, 0.1, 2])
print(repr(arr))  # upcasting

array([0. , 0.1, 2. ])


In [5]:
a = np.array([3,6])
b = np.array([6,2])

c = a
d = b.copy()
print(f'Array a: {repr(a)}')

c[0] = 979
d[0] = 979

print(f'Array a: {repr(a)}')
print(repr(b))

#copy creates new array

      

Array a: array([3, 6])
Array a: array([979,   6])
array([6, 2])


In [7]:
arr = np.array([2,34,56,32])
print(arr.dtype)
arr = arr.astype(np.float32)  #CASTING
print(arr.dtype)

int64
float32


In [8]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


In [9]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in an OverflowError
np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


OverflowError: cannot convert float infinity to integer

In [14]:
arr = np.arange(1,5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [17]:
#To specify the number of elements in the returned array, 
#rather than the step size, we can use the np.linspace function.

arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

# arr = np.linspace(1, 100)  #default value 50
# print(repr(arr))


array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


In [19]:
arr = np.arange(8)
print(repr(arr))
reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))
#-1 will take on the value necessary to allow the new shape to contain all the elements of the array.
reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([0, 1, 2, 3, 4, 5, 6, 7])
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [20]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


In [25]:
arr = np.arange(12)
arr = np.reshape(arr, (-1, 2))
transposed = np.transpose(arr)
print(repr(arr))
print(repr(transposed))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])
array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])


In [26]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))
print(transposed.shape)

(4, 2, 3)


In [29]:
arr = np.array([[12,532,2345], [25,252,5773], [5205,352,52]])
print(repr(np.zeros_like(arr)))

arr = np.arange(24)
arr = np.reshape(arr, (2, 3, 4))
print(repr(np.ones_like(arr, dtype=np.float32)))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)


In [30]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [31]:
def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


In [32]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in ValueError
print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [34]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

4
1
5
array([[10, -1],
       [11, 11]])


In [35]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [36]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


In [40]:
print(np.random.uniform())
print(np.random.uniform(low=3, high=9))
print(repr(np.random.uniform(low=5, high=6, size=8)))
print(repr(np.random.uniform(low=-2, high=9, size=(9,3))))

0.518152548941889
8.190121511873901
array([5.82914691, 5.82960336, 5.27304997, 5.0592432 , 5.67052804,
       5.59306552, 5.6716541 , 5.41178788])
array([[ 0.17305988,  1.18592605, -0.43667851],
       [ 6.6164592 ,  2.53792726, -1.62411558],
       [ 4.86432985,  5.26699303,  1.28344824],
       [ 2.90747957,  0.44337002, -1.19299411],
       [ 3.16162379, -0.94210514,  7.93707183],
       [-0.68560485,  3.77279315, -1.08014695],
       [ 8.08547468,  8.0149322 ,  1.28823123],
       [ 4.42828033,  4.2250323 ,  4.7533215 ],
       [ 8.52189222,  0.87076878,  0.54116964]])


In [44]:
print(np.random.normal())
print(np.random.normal(loc=3, scale=4))
print(np.random.normal(loc=-3.1, scale=9, size=(6,2)))

0.34558367589718153
1.2979438280342872
[[-23.24894238  12.69857263]
 [ -5.47774027   4.51665021]
 [ 15.68059251   1.63830481]
 [  5.75428102 -20.39980012]
 [-11.15342706  -0.12943461]
 [  6.33731899   9.04909415]]


In [51]:
colors = ['red', 'green', 'blue', 'yellow']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=(3,2))))
print(repr(np.random.choice(colors, size=(3,5), p=[0.35, 0.10, 0.40, 0.15])))

yellow
array([['green', 'blue'],
       ['yellow', 'green'],
       ['green', 'red']], dtype='<U6')
array([['red', 'red', 'red', 'yellow', 'blue'],
       ['blue', 'blue', 'red', 'red', 'blue'],
       ['yellow', 'blue', 'red', 'blue', 'red']], dtype='<U6')
